development:
  adapter: postgresql
  encoding: utf8
  database: recipebox_development
  pool: 16
  username: postgres
  password: hyperion

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: recipebox_test
  pool: 16
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: recipebox_production
  pool: 16
  username: 
  password: